dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "XuanCe_Benchmark"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: False
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
test_mode: False
device: "cuda:0"

agent: "TD3"
env_name: "Drones"
env_id: "DenseObstacles"
obs_type: 'kin'
act_type: 'vel'
num_drones: 1
record: False
obstacles: True
sleep: 0
max_episode_steps: 2000  #
vectorize: "Dummy_Drone"
policy: "TD3_Policy"
representation: "Basic_Identical"
runner: "DRL"

representation_hidden_size:  # If you choose Basic_Identical representation, then ignore this value
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "leaky_relu"
activation_action: 'tanh'
seed: 1
parallels: 8
buffer_size: 800000
batch_size: 256
actor_learning_rate: 0.001
actor_update_delay: 3
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.25
end_noise: 0.05
training_frequency: 2
running_steps: 10000000 # total step
start_training: 2000

use_grad_clip: False  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 10000
test_episode: 5
log_dir: "./logs/td3/"
model_dir: "./models/td3/"