dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "XuanCe_Benchmark"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: False
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
test_mode: False
device: "cuda:0"

agent: "DDPG"
env_name: "Drones"
env_id: "DenseObstacles"
obs_type: 'kin'
act_type: 'vel'
num_drones: 1
record: False
obstacles: True
sleep: 0
max_episode_steps: 2000  #
vectorize: "Dummy_Drone"
policy: "DDPG_Policy"
representation: "Basic_Identical"
runner: "DRL"

actor_hidden_size: [64, 64]
critic_hidden_size: [64, 64]
activation: "leaky_relu"
activation_action: "tanh"

seed: 1
parallels: 10
buffer_size: 8000000  # buffer
batch_size: 1024
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.1
end_noise: 0.1
training_frequency: 1
running_steps: 10000000 # total step
start_training: 2000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 10000
test_episode: 5
log_dir: "./logs/ddpg/"
model_dir: "./models/ddpg/"
model_folder: ''